### ISSUE TITLE
Routing issue when sending both api-key and authorization in header in v0.10.0

### ISSUE THREAD

**Issue by LeonKalt** [timoklimmer/powerproxy-aoai#79] opened 2024-05-27 15:25 UTC
When sending both **api-key** and **authorization** header as done per default in the open ai python lib. A **entra_id_client** must be set or the powerproxy generates an exception. 

[openai/lib/azure.py](https://github.com/openai/openai-python/blob/main/src/openai/lib/azure.py#L533)

**Comment by timoklimmer** [comment] 2024-05-27 17:04
Hi @LeonKalt, the problem you bring up is encountered when an Entra ID/Azure AD request is sent, but PowerProxy's configuration misses a client that is marked as the entra id client. Use `uses_entra_id_auth: true` instead of `key: ...` to mark the client used for Entra ID requests. This is expected behavior / by design because PowerProxy has no other option to identify a client in case of Entra ID auth other than using a fixed client. I have updated the code and released a new version which should give a better error response / explanation when this scenario is encountered.

**Closed by timoklimmer** 2024-05-27 17:04 UTC

**Comment by PhMueller** [comment] 2024-05-28 06:16
Hey @timoklimmer, 

first of all, thanks for your fast response and your work here! The Powerproxy is very useful for us. 

Unfortunately, that did not solve the error, @LeonKalt described, for us. 

To provide some more context, we call the PP by using langchain. 
We also do not make an AD request, but simply provide the address of the PP as endpoint, together with the api key. 

I totally understand your point, but the `openai` lib attaches `Authorization`  always to the header. 
At least, that happens in our situation. 
(See here: https://github.com/openai/openai-python/blob/main/src/openai/_client.py#L370)

Therefore, if we make a request, both, "api-key" and "Authorization" is given. 

We have bypassed the problem by changing the workflow in your PP a bit. 
By changing the "if" to an  "elif", it works for us. 
 
https://github.com/timoklimmer/powerproxy-aoai/blob/main/app/powerproxy.py#L218

```diff
-         if "authorization" in headers:
+         elif "authorization" in headers: 
```

What do you think about this approach?

**Comment by timoklimmer** [comment] 2024-05-28 09:20
I have tested with the latest openai package and have sent a request with both API key and Authorization token, and it worked without issues. If both API key and auth token are sent, the auth token wins as desired (although it's a bad request anyway IMHO). I suggest to check your code and configuration again. The test scripts included in the repo show how to send requests via the openai package.
